### ISSUE TITLE
Informers stop working on AKS after ~30min

### ISSUE THREAD

**Issue by IvanJosipovic** [IvanJosipovic/KubeUI#458]
The Informers stop working when connecting to AKS after ~30mins.

**Comment by IvanJosipovic** [comment]
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.ListClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
at KubeUI.Core.Client.Informer.ResourceInformer`1.ListAsync(CancellationToken cancellationToken)
at KubeUI.Core.Client.Informer.ResourceInformer`1.RunAsync(CancellationToken cancellationToken)
```


```
System.Net.Http.HttpProtocolException: The HTTP/2 server reset the stream. HTTP/2 error code 'INTERNAL_ERROR' (0x2).
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadData(Span`1 buffer, HttpResponseMessage responseMessage)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at k8s.KubernetesJson.Deserialize[TValue](Stream json, JsonSerializerOptions jsonSerializerOptions) in C:\\Repos\\kubernetes-client-csharp\\src\\KubernetesClient.Models\\KubernetesJson.cs:line 91
   at k8s.Kubernetes.CreateResultAsync[T](HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, Nullable`1 watch, CancellationToken cancellationToken) in C:\\Repos\\kubernetes-client-csharp\\src\\KubernetesClient\\Kubernetes.cs:line 90
   at k8s.AbstractKubernetes.k8s.ICustomObjectsOperations.ListClusterCustomObjectWithHttpMessagesAsync(String group, String version, String plural, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken) in C:\\Repos\\kubernetes-client-csharp\\src\\KubernetesClient.Basic\\LibKubernetesGenerator\\LibKubernetesGenerator.KubernetesClientSourceGenerator\\CustomObjectsOperations.g.cs:line 107
   at KubeUI.Core.Client.Informer.ResourceInformer`1.ListAsync(CancellationToken cancellationToken) in C:\\Repos\\KubeUI\\src\\KubeUI.Core\\Client\\Informer\\ResourceInformer.cs:line 196
   at KubeUI.Core.Client.Informer.ResourceInformer`1.RunAsync(CancellationToken cancellationToken) in C:\\Repos\\KubeUI\\src\\KubeUI.Core\\Client\\Informer\\ResourceInformer.cs:line 127
```
