### ISSUE TITLE
Connect to AKS kluster fails on MacOS Sequoia

### ISSUE THREAD

**Issue by Zigby** [IvanJosipovic/KubeUI#761]
When trying to connect to AKS cluster on from a  PC running MacOS Sequoia I get a KeyChain error, see exception below. Works fine on PC running WIndows 11. Seem to be an issue regarding how .net  integration with Mac OS works. There was a fix in 8.0.403 regarding creation of self-signed certificates and the same should be in the latest .net9.0 I assume. The required information is in the kube config file, but somehow the keychain anyways gets involved? ON MacOS it works fine to connect to local cluster running Rancher Desktop.

Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.
   at Interop.AppleCrypto.X509CopyWithPrivateKey(SafeSecCertificateHandle certHandle, SafeSecKeyRefHandle privateKeyHandle, SafeKeychainHandle targetKeychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.ExtractKeyFromPem[TAlg](ReadOnlySpan`1 keyPem, String[] labels, Func`1 factory, Func`2 import)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(ReadOnlySpan`1 certPem, ReadOnlySpan`1 keyPem)
   at k8s.CertUtils.GeneratePfx(KubernetesClientConfiguration config)
   at k8s.CertUtils.GetClientCert(KubernetesClientConfiguration config)
   at k8s.Kubernetes.InitializeFromConfig(KubernetesClientConfiguration config)
   at k8s.Kubernetes..ctor(KubernetesClientConfiguration config, DelegatingHandler[] handlers)
   at KubeUI.Client.Cluster.Connect() in /Users/jan/Source/GitHub/KubeUI/src/KubeUI/Client/Cluster.cs:line 115

**Comment by Zigby** [comment]
I recompiled the apha branch using .net8  (sdk version 8.0.403) instead of .net9 (9.0.100-rc.2.24474.11) and then it worked, I could connect to AKS cluster from MacOS Sequoia without any certificate problems. Hopefully this issue will be fixed in next 9.0 version as well.

**Comment by IvanJosipovic** [comment]
Hey, thanks for this report, please let me know if this is not resolved once I update to 9 RTM.

**Comment by IvanJosipovic** [comment]
Hey, https://github.com/IvanJosipovic/KubeUI/releases/tag/v1.0.0-alpha.88 is now on .NET 9 RTM. Let me know if this issue re-appears.
